### ISSUE TITLE
0.01 소스 관련

### ISSUE THREAD

**Issue by paranlee** [YWHyuk/linux-kernel-0.01#1]
https://mirrors.edge.kernel.org/pub/linux/kernel/

https://mirrors.edge.kernel.org/pub/linux/kernel/Historic/linux-0.01.tar.gz
Original Source Code가 위의 파일인가요?

**Comment by YWHyuk** [comment]
네 맞습니다. 다운받아서 사용하시거나 이 레파지토리의 첫번째 커밋을 사용하셔도 되요
